@startjson
  title JSON Data
{
  "User": {
    "id": "1",
    "login": "KravhiLena",
    "password": "24062004",
    "Photo": "url фото",
    "email": "kravhi@gmail.com",
    "userName": "KravhiLena",
    "Requests new sets of exercises": [
      {
        "id": "1",
        "purpose": "Я хотіла б отримати нові комплекси вправ для тренування на все тіло, будь-ласка",
        "date": "09.10.2023",
        "user id": "1"
      },
      {
        "id": "2",
        "purpose": "Хотілось комплекси по-складніше,будь-ласка!",
        "date": "09.10.2023",
        "user id": "1"
      }
    ],
    "Expense record": [
      {
        "id": "1",
        "weight": "55",
        "Training time": "80",
        "user id": "1"
      },
      {
        "id": "2",
        "weight": "50",
        "Training time": "40",
        "user id": "1"
      }
    ],
    "Motivational message": {
      "id": "1",
      "response text": "Ти молодець! З кожним разом результат в тебе краще. Дуже стараєшся, але можна зменшити час тренування.",
      "user id": "1"
    }
  },
  "Trainer": {
    "id": "1",
    "specialization": "Фітнес тренер",
    "user id": "2",
    "Answer to the requests": [
      {
        "id": "1",
        "response text": "Ось такий варіант: ",
        "date": "09.10.2023",
        "request id": 1
      },
      {
        "id": "2",
        "response text": "Ось такі вправи:",
        "date": "09.10.2023",
        "request id": 2
      }
    ]
  }
}
@endjson
