@startuml

hide circle
title UML Concept Classes

Class User {
    login
    password
}

CLass UserInformation {
    Photo
    email
    userName
}

Class ExerciseRequest{
    purpose
    date
}

Class Trainer {
    specialization
}

User <|-- Trainer

UserInformation o-- User

User"1" --> "*"ExerciseRequest : send

Trainer"1" --> "*"ExerciseRequest : review

@enduml
